version: '3.8'

services:
  lead-time:
    build: lead-time/
    ports:
      - "8001:8001"

  backend:
    build: ./taigaProject
    ports:
      - "8000:8000"

  frontend:
    build: ./react-ui
    ports:
      - "3000:3000"
