version: '3.8'

services:
  cycle-time:
    build: cycle-time/
    ports:
      - "8002:8002"

  backend:
    build: ./taigaProject
    ports:
      - "8000:8000"

  frontend:
    build: ./react-ui
    ports:
      - "3000:3000"
