version: '3.8'

services:
  gateway:
    build: ./APIGateway
    ports:
      - "8000:8000"

  backend:
    build: ./taigaProject
    ports:
      - "8001:8001"

  frontend:
    build: ./react-ui
    ports:
      - "3000:3000"
