version: '3.8'

services:
  lead-time:
    build: lead-time/
    ports:
      - "8001:8001"

  cycle-time:
    build: cycle-time/
    ports:
      - "8002:8002"

  dev-focus:
    build: dev-focus/
    ports:
      - "8003:8003"
  cruft:
    build: cruft/
    ports:
      - "8005:8005"

  backend:
    build: ./taigaProject
    ports:
      - "8000:8000"

  frontend:
    build: ./react-ui
    ports:
      - "3000:3000"
